apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "static-webhost.fullname" . }}-caddy
  labels:
    {{- include "static-webhost.labels" . | nindent 4 }}
    app.kubernetes.io/component: caddy
data:
  Caddyfile: |
    {
      frankenphp
      auto_https off
      {{- with .Values.caddy.trustedProxies }}
      servers {
        trusted_proxies static {{ join " " . }}
        client_ip_headers X-Forwarded-For
      }
      {{- end }}
    }

    :8080 {
      encode zstd br gzip
      {{- range $g := .Values.domainGroups }}
      {{- range $d := $g.domains }}
      @{{ include "static-webhost.matcher" $d.name }} host {{ $d.name }}
      handle @{{ include "static-webhost.matcher" $d.name }} {
        root * /srv/{{ $g.name }}/{{ $d.name }}
        {{- if $d.writablePaths }}
        {{- range $p := $d.writablePaths }}
        handle /{{ $p }}/* {
          respond 404
        }
        {{- end }}
        handle {
          php_server {
            env REMOTE_ADDR {client_ip}
          }
        }
        {{- else }}
        php_server {
          env REMOTE_ADDR {client_ip}
        }
        {{- end }}
      }
      {{- end }}
      {{- end }}
      handle {
        respond 404
      }
    }
  prepend.php: |
    <?php
    ini_set('open_basedir', $_SERVER['DOCUMENT_ROOT'] . ':/tmp');
  webhost.ini: |
    auto_prepend_file = /etc/frankenphp/prepend.php
