apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "static-webhost.fullname" . }}-caddy
  labels:
    {{- include "static-webhost.labels" . | nindent 4 }}
    app.kubernetes.io/component: caddy
data:
  Caddyfile: |
    {
      frankenphp
      auto_https off
    }

    :8080 {
      root * /srv
      encode zstd br gzip
      php_server
    }
