{{- range $g := .Values.domainGroups }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "static-webhost.codeServerName" (dict "Context" $ "Group" $g.name) }}
  labels:
    {{- include "static-webhost.labels" $ | nindent 4 }}
    app.kubernetes.io/component: code-server
    webhost.gewis.nl/group: {{ $g.name }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "static-webhost.codeServerSelectorLabels" (dict "Context" $ "Group" $g.name) | nindent 4 }}
{{- end }}
