apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "static-webhost.fullname" . }}-code-server-settings
  labels:
    {{- include "static-webhost.labels" . | nindent 4 }}
    app.kubernetes.io/component: code-server
data:
  settings.json: |
    {{- .Values.codeServer.settings | toPrettyJson | nindent 4 }}
