{{- $fullName := include "static-webhost.fullname" . -}}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "static-webhost.labels" . | nindent 4 }}
spec:
  entryPoints:
    - websecure
  routes:
    {{- range $g := .Values.domainGroups }}
    {{- $csName := include "static-webhost.codeServerName" (dict "Context" $ "Group" $g.name) }}
    {{- range $d := $g.domains }}
    - kind: Rule
      match: Host(`{{ $d.name }}`)
      services:
        - name: {{ $fullName }}-caddy
          port: 80
    - kind: Rule
      match: Host(`{{ $d.name }}`) && PathPrefix(`/admin`)
      middlewares:
        - name: {{ $fullName }}-admin-slash
        - name: {{ $fullName }}-auth-{{ $g.name }}
        - name: {{ $fullName }}-strip-admin
      services:
        - name: {{ $csName }}
          port: 8080
    {{- end }}
    {{- if $g.adminDomain }}
    - kind: Rule
      match: Host(`{{ $g.adminDomain }}`)
      middlewares:
        - name: {{ $fullName }}-auth-{{ $g.name }}
      services:
        - name: {{ $csName }}
          port: 8080
    {{- end }}
    {{- end }}
