apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "static-webhost.fullname" . }}-data
  labels:
    {{- include "static-webhost.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.storage.size | quote }}
